[package]
name = "rust_search"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
needletail = "0.5"
rayon = "1.8"
aho-corasick = "1.1"
libc = "0.2"

[build-dependencies]
cc = "1.0"

[profile.release]
debug = true
